// 전국 봄꽃 명소 60+ 데이터 — 꽃맵 (flower.weknews.com)

export type Region = "서울/경기" | "강원" | "충청/대전" | "전라/광주" | "경상/부산" | "제주";
export type BloomStatus = "없음" | "꽃봉오리" | "개화시작" | "만개" | "절정" | "낙화";

export interface Spot {
  id: number;
  name: string;
  region: Region;
  address: string;
  lat: number;
  lng: number;
  flowerIds: string[];       // flowers.ts의 id 참조
  peakMonth: number;         // 절정 월 (1~12)
  peakStartDate: string;     // "3.25" 형식
  peakEndDate: string;
  status: BloomStatus;       // 현재 개화 상태 (수동 업데이트)
  tags: string[];
  description: string;
  parking: string;
  tip: string;
  imageKeyword: string;      // Unsplash 이미지 검색 키워드
  festivalName?: string;     // 연관 축제명
}

export const SPOTS: Spot[] = [
  // ===== 서울/경기 =====
  {
    id: 1,
    name: "여의도 윤중로 벚꽃길",
    region: "서울/경기",
    address: "서울특별시 영등포구 여의도동",
    lat: 37.5261, lng: 126.9333,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.12",
    status: "없음",
    tags: ["벚꽃", "도심", "산책", "한강"],
    description: "서울 최대 벚꽃 명소. 윤중로 1.7km 구간에 천여 그루의 벚꽃이 만개합니다.",
    parking: "여의도 한강공원 주차장 이용 (주말 혼잡, 대중교통 강력 추천)",
    tip: "이른 아침(07시 이전) 방문 시 인파 없이 조용하게 즐길 수 있습니다.",
    imageKeyword: "cherry blossom Seoul Yeouido",
    festivalName: "서울 영등포 여의도 봄꽃축제"
  },
  {
    id: 2,
    name: "올림픽공원 장미광장",
    region: "서울/경기",
    address: "서울특별시 송파구 방이동 올림픽공원",
    lat: 37.5214, lng: 127.1247,
    flowerIds: ["jangmi", "tulip"],
    peakMonth: 5, peakStartDate: "5.20", peakEndDate: "6.10",
    status: "없음",
    tags: ["장미", "튤립", "가족", "도심"],
    description: "장미 4,000그루와 튤립이 만발하는 서울 대표 봄꽃 공원. 입장료 없이 즐길 수 있습니다.",
    parking: "올림픽공원 주차장 (유료)",
    tip: "혜화문, 평화의 문 앞 장미터널이 사진 명소입니다.",
    imageKeyword: "rose garden Seoul Olympic Park"
  },
  {
    id: 3,
    name: "석촌호수 벚꽃",
    region: "서울/경기",
    address: "서울특별시 송파구 석촌호수 일대",
    lat: 37.5078, lng: 127.1038,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.3", peakEndDate: "4.10",
    status: "없음",
    tags: ["벚꽃", "도심", "데이트", "호수"],
    description: "롯데월드 앞 호수를 둘러싼 벚꽃 산책로. 야간 조명과 어우러지는 야경 벚꽃이 절경입니다.",
    parking: "주변 유료주차장 (지하철 잠실역 도보 5분 추천)",
    tip: "야간 벚꽃 라이트업이 운영되어 저녁 방문도 추천합니다.",
    imageKeyword: "cherry blossom Seokchon Lake Seoul"
  },
  {
    id: 4,
    name: "서울대공원 장미원",
    region: "서울/경기",
    address: "경기도 과천시 막계동 서울대공원",
    lat: 37.4315, lng: 127.0174,
    flowerIds: ["jangmi", "tulip"],
    peakMonth: 5, peakStartDate: "5.25", peakEndDate: "6.15",
    status: "없음",
    tags: ["장미", "가족", "수목원", "동물원"],
    description: "국내 최대 규모의 장미원. 50여 종 4만 본의 장미가 형형색색 피어납니다.",
    parking: "서울대공원 주차장 완비",
    tip: "동물원과 함께 방문하면 아이들도 좋아합니다.",
    imageKeyword: "rose garden Seoul Grand Park Gwacheon"
  },
  {
    id: 5,
    name: "고양 꽃박람회 (일산)",
    region: "서울/경기",
    address: "경기도 고양시 일산동구 호수공원",
    lat: 37.6611, lng: 126.7799,
    flowerIds: ["tulip", "mokryeon"],
    peakMonth: 4, peakStartDate: "4.20", peakEndDate: "5.10",
    status: "없음",
    tags: ["튤립", "꽃박람회", "가족", "축제"],
    description: "연간 200만 명이 찾는 전국 최대 봄꽃 박람회. 다양한 수목류와 튤립 전시가 압도적입니다.",
    parking: "일산 호수공원 주차장 (박람회 기간 조기 만차)",
    tip: "개장 시간(09시) 맞춰 방문하면 가장 여유롭습니다.",
    imageKeyword: "Goyang flower festival tulip Korea",
    festivalName: "고양국제꽃박람회"
  },
  {
    id: 6,
    name: "가평 삼회리 벚꽃길",
    region: "서울/경기",
    address: "경기도 가평군 삼회리",
    lat: 37.7890, lng: 127.4802,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["벚꽃", "드라이브", "당일치기", "한적"],
    description: "북한강변을 따라 펼쳐지는 벚꽃 드라이브 코스. 사람이 많지 않아 조용하게 즐길 수 있습니다.",
    parking: "길가 공터 주차 가능",
    tip: "강변도로를 따라 창문 열고 드라이브하면 최고의 봄날입니다.",
    imageKeyword: "cherry blossom Gapyeong riverside"
  },
  {
    id: 7,
    name: "에버랜드 튤립",
    region: "서울/경기",
    address: "경기도 용인시 처인구 에버랜드로",
    lat: 37.2936, lng: 127.2017,
    flowerIds: ["tulip", "wangbeotkkot"],
    peakMonth: 4, peakStartDate: "4.10", peakEndDate: "5.5",
    status: "없음",
    tags: ["튤립", "테마파크", "가족", "유채"],
    description: "스프링 페스티벌 기간 100만 본 이상의 꽃이 피는 대규모 봄꽃 이벤트.",
    parking: "에버랜드 주차장 (유료)",
    tip: "스프링 페스티벌 날짜 확인 후 방문하세요.",
    imageKeyword: "Everland tulip spring festival Korea",
    festivalName: "에버랜드 스프링 페스티벌"
  },
  {
    id: 8,
    name: "인천 자유공원 벚꽃",
    region: "서울/경기",
    address: "인천광역시 중구 자유공원",
    lat: 37.4774, lng: 126.6215,
    flowerIds: ["beotkkot", "gaenari"],
    peakMonth: 4, peakStartDate: "4.3", peakEndDate: "4.12",
    status: "없음",
    tags: ["벚꽃", "개나리", "역사", "도심"],
    description: "인천 최초의 공원. 언덕을 따라 벚꽃과 개나리가 함께 어우러집니다.",
    parking: "자유공원 인근 공영주차장",
    tip: "공원 꼭대기에서 인천항이 한눈에 보이는 뷰가 멋집니다.",
    imageKeyword: "cherry blossom Incheon Freedom Park"
  },

  // ===== 강원 =====
  {
    id: 9,
    name: "강릉 경포호 벚꽃",
    region: "강원",
    address: "강원도 강릉시 경포로",
    lat: 37.7904, lng: 128.8780,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.8", peakEndDate: "4.18",
    status: "없음",
    tags: ["벚꽃", "호수", "드라이브", "바다"],
    description: "경포호 주변 벚꽃 가로수길. 바다와 호수, 벚꽃이 동시에 어우러지는 독특한 경관.",
    parking: "경포해변 공영주차장",
    tip: "자전거 대여 후 경포호 일주 코스로 즐기는 것을 추천합니다.",
    imageKeyword: "cherry blossom Gyeongpo Lake Gangneung"
  },
  {
    id: 10,
    name: "삼척 죽서루 벚꽃",
    region: "강원",
    address: "강원도 삼척시 성내동 죽서루",
    lat: 37.4497, lng: 129.1621,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.10", peakEndDate: "4.20",
    status: "없음",
    tags: ["벚꽃", "문화재", "한적", "강원"],
    description: "오십천변 절벽 위 누각과 벚꽃의 조화가 아름다운 숨은 명소.",
    parking: "죽서루 공영주차장",
    tip: "삼척 해수욕장과 함께 당일 코스로 구성하면 좋습니다.",
    imageKeyword: "cherry blossom Samcheok Jukseoru"
  },

  // ===== 충청/대전 =====
  {
    id: 11,
    name: "공주 마곡사 봄꽃",
    region: "충청/대전",
    address: "충청남도 공주시 사곡면 마곡사로",
    lat: 36.5322, lng: 126.9108,
    flowerIds: ["beotkkot", "jindalrae"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.18",
    status: "없음",
    tags: ["벚꽃", "절", "숲길", "UNESCO"],
    description: "유네스코 세계유산 마곡사의 봄꽃 산책로. 고즈넉한 분위기 속 봄꽃을 즐길 수 있습니다.",
    parking: "마곡사 주차장",
    tip: "해탈문 앞 연못 반영 사진이 명소입니다.",
    imageKeyword: "Magoksa temple spring flowers Korea"
  },
  {
    id: 12,
    name: "대전 대청호 벚꽃길",
    region: "충청/대전",
    address: "충청북도 청주시 상당구 문의면",
    lat: 36.5006, lng: 127.5252,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.7", peakEndDate: "4.17",
    status: "없음",
    tags: ["벚꽃", "드라이브", "호수", "당일치기"],
    description: "대청호를 끼고 펼쳐지는 벚꽃 드라이브 코스. 벚꽃과 수면 반영이 환상적입니다.",
    parking: "대청호 오백리길 주차장",
    tip: "차량 드라이브 코스로 최적. 창문 열고 달리면 꽃비 체험 가능.",
    imageKeyword: "cherry blossom Daecheong Lake Daejeon"
  },
  {
    id: 13,
    name: "서산 개심사 겹벚꽃",
    region: "충청/대전",
    address: "충청남도 서산시 운산면 개심사로",
    lat: 36.7268, lng: 126.5213,
    flowerIds: ["kyupbeotkkot"],
    peakMonth: 4, peakStartDate: "4.20", peakEndDate: "4.30",
    status: "없음",
    tags: ["겹벚꽃", "절", "분홍팝콘", "한적"],
    description: "'분홍 팝콘'이 가득한 겹벚꽃 명소. 400년 고찰과 어우러진 봄꽃이 압도적입니다.",
    parking: "개심사 입구 주차장",
    tip: "벚꽃 이후 방문해야 겹벚꽃이 만개합니다. 시기 확인 필수.",
    imageKeyword: "Gaesimsa temple double cherry blossom Seosan"
  },

  // ===== 전라/광주 =====
  {
    id: 14,
    name: "광양 매화마을",
    region: "전라/광주",
    address: "전라남도 광양시 다압면 매화로",
    lat: 35.0822, lng: 127.7228,
    flowerIds: ["maehwa"],
    peakMonth: 3, peakStartDate: "3.10", peakEndDate: "3.20",
    status: "없음",
    tags: ["매화", "축제", "섬진강", "봄의 전령"],
    description: "전국 최대 규모의 매화 군락지. 섬진강변을 따라 매화가 만발하면 봄이 시작되었음을 알립니다.",
    parking: "매화마을 공영주차장",
    tip: "이른 아침 안개 속 매화 뷰가 장관. 섬진강 뷰카페도 추천.",
    imageKeyword: "plum blossom Gwangyang Seomjin River",
    festivalName: "광양 매화축제"
  },
  {
    id: 15,
    name: "구례 산수유마을",
    region: "전라/광주",
    address: "전라남도 구례군 산동면 지리산온천로",
    lat: 35.2215, lng: 127.5196,
    flowerIds: ["sansuyu"],
    peakMonth: 3, peakStartDate: "3.12", peakEndDate: "3.22",
    status: "없음",
    tags: ["산수유", "축제", "지리산", "노란 물결"],
    description: "지리산 자락 600년 역사의 산수유 마을. 온 마을이 노란빛으로 물드는 장관.",
    parking: "산수유마을 공영주차장",
    tip: "꽃차 체험, 산수유 한과 만들기 등 다양한 체험 프로그램 운영.",
    imageKeyword: "cornelian cherry Gurye village Jirisan",
    festivalName: "구례 산수유꽃축제"
  },
  {
    id: 16,
    name: "담양 메타세콰이아 & 봄꽃",
    region: "전라/광주",
    address: "전라남도 담양군 담양읍 학동리",
    lat: 35.3233, lng: 126.9818,
    flowerIds: ["beotkkot", "gaenari"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["벚꽃", "메타세콰이아", "드라이브", "영화세트"],
    description: "영화 '내 머리 속의 지우개' 촬영지. 메타세콰이아 가로수길에 봄꽃이 피면 환상적입니다.",
    parking: "메타세콰이아랜드 주차장",
    tip: "죽녹원 대나무숲과 함께 당일 코스로 묶으면 좋습니다.",
    imageKeyword: "Metasequoia road Damyang spring"
  },
  {
    id: 17,
    name: "고창 청보리밭 & 유채꽃",
    region: "전라/광주",
    address: "전라북도 고창군 공음면 선동리",
    lat: 35.3929, lng: 126.6461,
    flowerIds: ["yuche"],
    peakMonth: 4, peakStartDate: "4.15", peakEndDate: "5.5",
    status: "없음",
    tags: ["유채꽃", "청보리", "광활", "인스타"],
    description: "청보리밭 사이로 유채꽃이 함께 피어나는 장관. 광활한 풍경이 마치 유럽의 시골 같습니다.",
    parking: "학원 농장 주차장 (유료)",
    tip: "유채꽃 시즌에 맞춰 학원농장 청보리&유채꽃 축제가 열립니다.",
    imageKeyword: "green barley field canola flower Gochang",
    festivalName: "고창 청보리밭 축제"
  },
  {
    id: 18,
    name: "함평 작약꽃 축제",
    region: "전라/광주",
    address: "전라남도 함평군 함평읍",
    lat: 35.0655, lng: 126.5177,
    flowerIds: ["jakak"],
    peakMonth: 5, peakStartDate: "5.10", peakEndDate: "5.25",
    status: "없음",
    tags: ["작약", "축제", "꽃의 여왕"],
    description: "풍성한 작약꽃이 가득한 봄꽃 축제. 다양한 색의 작약이 군락을 이룹니다.",
    parking: "행사장 주차장 마련",
    tip: "오전 방문 시 꽃잎이 가장 활짝 펴있습니다.",
    imageKeyword: "peony flower festival Hampyeong Korea",
    festivalName: "함평 나비·작약 축제"
  },

  // ===== 경상/부산 =====
  {
    id: 19,
    name: "진해 군항제 (여좌천)",
    region: "경상/부산",
    address: "경상남도 창원시 진해구 여좌천로",
    lat: 35.1440, lng: 128.6637,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "3.30", peakEndDate: "4.10",
    status: "없음",
    tags: ["벚꽃", "군항제", "로망스 다리", "전국 최대"],
    description: "전국 벚꽃 축제의 성지. 300만 그루 벚꽃이 도시 전체를 뒤덮습니다. 여좌천 로망스 다리가 필수 코스.",
    parking: "진해역 주변 주차장 (셔틀버스 이용 강력 추천)",
    tip: "군항제 기간 인파 극심. 평일 방문하거나 이른 아침 방문하세요.",
    imageKeyword: "Jinhae Cherry Blossom Festival Yeojwa",
    festivalName: "진해 군항제"
  },
  {
    id: 20,
    name: "경주 보문단지 벚꽃",
    region: "경상/부산",
    address: "경상북도 경주시 보문동 보문호",
    lat: 35.8437, lng: 129.2666,
    flowerIds: ["beotkkot", "kyupbeotkkot"],
    peakMonth: 4, peakStartDate: "4.3", peakEndDate: "4.20",
    status: "없음",
    tags: ["벚꽃", "겹벚꽃", "호수", "역사"],
    description: "보문호를 둘러싼 벚꽃과 겹벚꽃. 신라 유적지와 어우러진 특별한 봄꽃 경관.",
    parking: "보문단지 공영주차장",
    tip: "불국사 겹벚꽃과 함께 묶어서 경주 당일치기 코스로 최적.",
    imageKeyword: "Gyeongju Bomun Lake cherry blossom"
  },
  {
    id: 21,
    name: "경주 불국사 겹벚꽃",
    region: "경상/부산",
    address: "경상북도 경주시 불국로 불국사",
    lat: 35.7888, lng: 129.3319,
    flowerIds: ["kyupbeotkkot"],
    peakMonth: 4, peakStartDate: "4.18", peakEndDate: "4.28",
    status: "없음",
    tags: ["겹벚꽃", "UNESCO", "사찰", "분홍팝콘"],
    description: "유네스코 세계문화유산 불국사의 겹벚꽃. '분홍 팝콘'이 천왕문 앞에 가득 피어납니다.",
    parking: "불국사 주차장 (유료)",
    tip: "일반 벚꽃보다 2주 늦게 핌. 개화 시기 정보 확인 후 방문하세요.",
    imageKeyword: "Bulguksa double cherry blossom Gyeongju"
  },
  {
    id: 22,
    name: "하동 십리벚꽃길",
    region: "경상/부산",
    address: "경상남도 하동군 화개면 화개동",
    lat: 35.1988, lng: 127.7001,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.1", peakEndDate: "4.12",
    status: "없음",
    tags: ["벚꽃", "섬진강", "드라이브", "사랑"],
    description: "4km 벚꽃 터널 드라이브 코스. '혼례길'로도 불리며 커플 명소로 유명합니다.",
    parking: "화개장터 주변 주차장",
    tip: "화개장터 → 쌍계사 방향으로 이동하며 드라이브하면 최적.",
    imageKeyword: "Hadong Hwagae cherry blossom road Seomjin"
  },
  {
    id: 23,
    name: "합천 황매산 철쭉제",
    region: "경상/부산",
    address: "경상남도 합천군 가회면 황매산",
    lat: 35.4882, lng: 128.0490,
    flowerIds: ["cheonjuk"],
    peakMonth: 5, peakStartDate: "5.1", peakEndDate: "5.15",
    status: "없음",
    tags: ["철쭉", "산", "전국 최대", "5월"],
    description: "전국 최대 규모의 철쭉 군락지. 황매산 정상부 일대가 진분홍빛으로 물드는 장관.",
    parking: "황매산 주차장 (철쭉제 기간 셔틀버스 운행)",
    tip: "철쭉제 기간 셔틀버스 예약 필수. 주말 방문 시 극심한 인파 예상.",
    imageKeyword: "azalea Hwangmaesan mountain Hapcheon",
    festivalName: "황매산 철쭉제"
  },
  {
    id: 24,
    name: "합천 핫들생태공원 작약",
    region: "경상/부산",
    address: "경상남도 합천군 합천읍 핫들생태공원",
    lat: 35.5660, lng: 128.1667,
    flowerIds: ["jakak"],
    peakMonth: 5, peakStartDate: "5.8", peakEndDate: "5.22",
    status: "없음",
    tags: ["작약", "생태공원", "5월", "당일치기"],
    description: "황매산 철쭉 이후 바통을 받는 5월 봄꽃의 마지막 주자. 화사한 작약꽃 군락이 장관.",
    parking: "핫들생태공원 주차장",
    tip: "황매산 철쭉 + 합천 작약 두 명소를 하루에 함께 즐길 수 있습니다.",
    imageKeyword: "peony Hapcheon ecological park"
  },
  {
    id: 25,
    name: "창녕 화왕산 진달래",
    region: "경상/부산",
    address: "경상남도 창녕군 창녕읍 화왕산",
    lat: 35.5332, lng: 128.5017,
    flowerIds: ["jindalrae"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["진달래", "산", "등산", "분화구"],
    description: "사화산의 분화구 분지 전체가 진달래로 가득 채워지는 독특하고 신비로운 명소.",
    parking: "화왕산 등산로 입구 주차장",
    tip: "정상 분화구까지 약 2시간 등산. 체력 준비 필요.",
    imageKeyword: "azalea Hwawangsan crater Changnyeong"
  },
  {
    id: 26,
    name: "부산 황령산 벚꽃",
    region: "경상/부산",
    address: "부산광역시 수영구 망미동 황령산",
    lat: 35.1497, lng: 129.0910,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.3", peakEndDate: "4.13",
    status: "없음",
    tags: ["벚꽃", "야경", "부산", "드라이브"],
    description: "부산 시내를 한눈에 내려다보며 벚꽃을 즐길 수 있는 드라이브 명소. 야경과 함께하면 특히 아름답습니다.",
    parking: "황령산 드라이브웨이 주변",
    tip: "낮과 야경 모두 아름다운 명소. 저녁 방문도 강력 추천.",
    imageKeyword: "cherry blossom Hwangnyeongsan Busan night view"
  },

  // ===== 제주 =====
  {
    id: 27,
    name: "제주 성산 유채꽃밭",
    region: "제주",
    address: "제주특별자치도 서귀포시 성산읍",
    lat: 33.4609, lng: 126.9268,
    flowerIds: ["yuche"],
    peakMonth: 2, peakStartDate: "2.1", peakEndDate: "3.31",
    status: "없음",
    tags: ["유채꽃", "성산일출봉", "제주", "봄의 시작"],
    description: "성산일출봉을 배경으로 펼쳐지는 유채꽃밭. 2월부터 3월까지 전국에서 가장 먼저 봄꽃을 볼 수 있는 곳.",
    parking: "성산일출봉 주차장",
    tip: "성산일출봉 입장권 구매 시 시야 확보를 위해 오전 이른 방문 권장.",
    imageKeyword: "Seongsan Ilchulbong canola yellow flower Jeju"
  },
  {
    id: 28,
    name: "제주 녹산로 유채꽃 도로",
    region: "제주",
    address: "제주특별자치도 서귀포시 표선면 녹산로",
    lat: 33.3497, lng: 126.8102,
    flowerIds: ["yuche"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.20",
    status: "없음",
    tags: ["유채꽃", "벚꽃", "드라이브", "제주"],
    description: "유채꽃과 벚꽃이 함께 피는 드라이브 명소. 노란색과 분홍색의 어우러짐이 절경입니다.",
    parking: "가시리 조랑말 체험공원 주차장",
    tip: "가시리 조랑말 체험관에서 말 체험 후 드라이브 코스 추천.",
    imageKeyword: "Noksan road canola cherry blossom Jeju drive"
  },
  {
    id: 29,
    name: "한라산 철쭉",
    region: "제주",
    address: "제주특별자치도 제주시 해발 1700m 이상",
    lat: 33.3617, lng: 126.5292,
    flowerIds: ["cheonjuk"],
    peakMonth: 5, peakStartDate: "5.10", peakEndDate: "5.25",
    status: "없음",
    tags: ["철쭉", "한라산", "등산", "백록담"],
    description: "1700m 이상 고지대에 펼쳐지는 철쭉 군락. 영실코스와 어리목코스를 따라 철쭉 천국이 펼쳐집니다.",
    parking: "영실 탐방로 주차장, 어리목 주차장",
    tip: "입산 통제 여부 사전 확인 필수. 이른 아침 출발 권장.",
    imageKeyword: "azalea Hallasan mountain Jeju spring"
  },

  // ===== 추가 명소 (ID 30 ~ 60) =====
  {
    id: 30,
    name: "서울 창경궁 백목련·벚꽃",
    region: "서울/경기",
    address: "서울특별시 종로구 창경궁로 185",
    lat: 37.5794, lng: 126.9950,
    flowerIds: ["mokryeon", "beotkkot"],
    peakMonth: 4, peakStartDate: "4.1", peakEndDate: "4.10",
    status: "없음",
    tags: ["목련", "벚꽃", "고궁", "한옥"],
    description: "고풍스러운 궁궐 전각과 흐드러지는 백목련, 벚꽃의 환상적인 조화. 춘당지 호수 둘레길이 명소입니다.",
    parking: "창경궁 주차장 (매우 협소, 대중교통 권장)",
    tip: "한복 입고 방문 시 Palace 무료 입장 및 감성 스냅 촬영 추천.",
    imageKeyword: "Changgyeonggung Palace magnolia cherry blossom Seoul"
  },
  {
    id: 31,
    name: "응봉산 개나리동산",
    region: "서울/경기",
    address: "서울특별시 성동구 응봉동 응봉산",
    lat: 37.5488, lng: 127.0371,
    flowerIds: ["gaenari"],
    peakMonth: 3, peakStartDate: "3.25", peakEndDate: "4.5",
    status: "없음",
    tags: ["개나리", "한강야경", "전망대", "봄시작"],
    description: "온 산이 노란 개나리로 뒤덮이는 서울의 대표 봄 산. 정상 팔각정에서 한강과 성수대교 야경을 함께 즐길 수 있습니다.",
    parking: "응봉역 공영주차장 이용",
    tip: "응봉역에서 정상 팔각정까지 도보 15분. 일몰 직전 올라가 야경까지 관람하세요.",
    imageKeyword: "Eungbongsan forsythia yellow mountain Seoul"
  },
  {
    id: 32,
    name: "부천 원미산 진달래동산",
    region: "서울/경기",
    address: "경기도 부천시 원미구 춘의동 원미산",
    lat: 37.5028, lng: 126.8042,
    flowerIds: ["jindalrae"],
    peakMonth: 4, peakStartDate: "4.1", peakEndDate: "4.12",
    status: "없음",
    tags: ["진달래", "진분홍", "산책로", "수도권명소"],
    description: "수도권 최대 진달래 군락지. 4만여 그루의 진달래가 만드는 진분홍 융단 산책로가 아기자기합니다.",
    parking: "부천 종합운동장 주차장 (지하철 7호선 부천종합운동장역 도보 5분)",
    tip: "부천종합운동장역 2번 출구에서 나와 산책로 따라 도보로 편하게 이동 가능.",
    imageKeyword: "Wonmisan azalea festival Bucheon"
  },
  {
    id: 33,
    name: "가평 자라섬 유채꽃·남도정원",
    region: "서울/경기",
    address: "경기도 가평군 가평읍 자라섬로 60",
    lat: 37.8178, lng: 127.5250,
    flowerIds: ["yuche", "tulip"],
    peakMonth: 5, peakStartDate: "5.1", peakEndDate: "5.20",
    status: "없음",
    tags: ["유채꽃", "강변", "정원", "캠핑"],
    description: "북한강 강변을 따라 펼쳐지는 샛노란 유채꽃과 무지개 빛깔 꽃정원. 사진작가들이 사랑하는 힐링 스팟입니다.",
    parking: "자라섬 입구 대형 주차장 (무료)",
    tip: "자라섬 남도 꽃정원 둘레길을 걸으며 강바람과 꽃향기를 동시에 느껴보세요.",
    imageKeyword: "Jarasum island canola flower garden Gapyeong"
  },
  {
    id: 34,
    name: "서초 양재천 조팝나무·벚꽃길",
    region: "서울/경기",
    address: "서울특별시 서초구 양재동 양재천",
    lat: 37.4764, lng: 127.0425,
    flowerIds: ["jopap", "beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["조팝나무", "벚꽃", "하천", "산책"],
    description: "하얀 조팝나무 눈송이 꽃과 분홍빛 벚꽃이 양재천 물길을 따라 평화롭게 피어나는 도심 힐링 산책로.",
    parking: "양재천 근린공원 주차장 또는 도곡역 이용",
    tip: "양재천 카페거리와 이어져 있어 꽃구경 후 커피 한 잔의 여유를 즐기기 좋습니다.",
    imageKeyword: "Yangjaecheon stream spiraea cherry blossom Seoul"
  },
  {
    id: 35,
    name: "양평 개군 산수유마을",
    region: "서울/경기",
    address: "경기도 양평군 개군면 내리 산수유길",
    lat: 37.4521, lng: 127.5612,
    flowerIds: ["sansuyu"],
    peakMonth: 3, peakStartDate: "3.20", peakEndDate: "4.5",
    status: "없음",
    tags: ["산수유", "돌담길", "시골", "드라이브"],
    description: "수령 백 년이 넘는 산수유나무 군락이 돌담길과 시냇가를 따라 고즈넉하게 피어나는 양평 대표 봄 마을.",
    parking: "개군 산수유마을 주차장",
    tip: "산수유 한우 먹거리 장터와 시골 돌담길 산책을 겸하면 풍성한 시골 여행이 완성됩니다.",
    imageKeyword: "Cornus officinalis Yangpyeong Sansuyu village"
  },
  {
    id: 36,
    name: "강릉 경포호 벚꽃길",
    region: "강원",
    address: "강원특별자치도 강릉시 경포동 경포호",
    lat: 37.7971, lng: 128.9083,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.14",
    status: "없음",
    tags: ["벚꽃", "경포호", "바다", "자전거"],
    description: "경포호수 4.3km 둘레길 전체가 분홍빛 벚꽃 터널로 변하는 동해안 최고의 벚꽃 명소.",
    parking: "경포대 주차장 및 호수 주변 공영주차장",
    tip: "자전거를 대여해 경포호수를 한 바퀴 돌며 바다와 호수 벚꽃을 한 번에 감상하세요.",
    imageKeyword: "Gyeongpo lake cherry blossom Gangneung"
  },
  {
    id: 37,
    name: "춘천 공지천 벚꽃 산책로",
    region: "강원",
    address: "강원특별자치도 춘천시 근화동 공지천",
    lat: 37.8722, lng: 127.7128,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.8", peakEndDate: "4.18",
    status: "없음",
    tags: ["벚꽃", "호수", "춘천", "데이트"],
    description: "의암호와 공지천 조각공원을 둘러싼 흐드러지는 벚꽃길. 피크닉 매트를 깔고 낭만을 즐기기 최적입니다.",
    parking: "공지천 조각공원 주차장",
    tip: "춘천 닭갈비 거리와 가깝고 오리배를 타며 호수 위 벚꽃을 구경할 수 있습니다.",
    imageKeyword: "Gongjicheon stream cherry blossom Chuncheon"
  },
  {
    id: 38,
    name: "삼척 맹방 유채꽃밭",
    region: "강원",
    address: "강원특별자치도 삼척시 근덕면 상맹방리",
    lat: 37.3878, lng: 129.2085,
    flowerIds: ["yuche", "beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.25",
    status: "없음",
    tags: ["유채꽃", "벚꽃", "동해바다", "축제"],
    description: "동해 7번 국도를 따라 가로수 벚꽃과 드넓은 노란 유채꽃이 동시 만개하는 강원 최대 유채꽃 축제장.",
    parking: "맹방 해수욕장 및 유채꽃 축제장 주차장",
    tip: "7번 국도 드라이브 코스와 맹방해변 BTS 포토존을 함께 코스로 묶으세요.",
    imageKeyword: "Maengbang canola flower Samcheok sea"
  },
  {
    id: 39,
    name: "태백산 국립공원 철쭉",
    region: "강원",
    address: "강원특별자치도 태백시 천제단길 165",
    lat: 37.1000, lng: 128.9167,
    flowerIds: ["cheonjuk"],
    peakMonth: 5, peakStartDate: "5.25", peakEndDate: "6.5",
    status: "없음",
    tags: ["철쭉", "태백산", "고원", "등산"],
    description: "해발 1500m 고원 능선에 피어나는 웅장하고 신비로운 진분홍 철쭉. 천제단과 어우러져 장관입니다.",
    parking: "유일사 주차장, 당골 광장 주차장",
    tip: "유일사 코스로 오르면 완만하게 태백산 정상 철쭉 능선에 도달할 수 있습니다.",
    imageKeyword: "Taebaeksan mountain royal azalea Taebaek"
  },
  {
    id: 40,
    name: "대전 대청호 십리벚꽃길",
    region: "충청/대전",
    address: "대전광역시 동구 신상동 대청호수로",
    lat: 36.3768, lng: 127.5098,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["벚꽃", "대청호", "드라이브", "대전"],
    description: "세계에서 가장 긴 26.6km의 호수 드라이브 벚꽃길. 호수 물빛과 벚꽃 터널이 이어집니다.",
    parking: "대청호 오백리길 방문객 주차장",
    tip: "드라이브 스루 벚꽃 관람 및 대청호 수변 데크길 산책을 강추합니다.",
    imageKeyword: "Daecheongho lake cherry blossom Daejeon drive"
  },
  {
    id: 41,
    name: "청주 무심천 벚꽃길",
    region: "충청/대전",
    address: "충청북도 청주시 상당구 무심천서로",
    lat: 36.6341, lng: 127.4891,
    flowerIds: ["beotkkot", "gaenari"],
    peakMonth: 4, peakStartDate: "4.3", peakEndDate: "4.12",
    status: "없음",
    tags: ["벚꽃", "개나리", "하천", "청주"],
    description: "청주 시민들이 가장 사랑하는 무심천 변 6km 벚꽃&개나리 통합 산책로.",
    parking: "무심천 체육공원 주차장",
    tip: "야간 루미나리에 조명이 밝혀져 밤에 걷기에도 낭만적입니다.",
    imageKeyword: "Musimcheon stream cherry blossom Cheongju"
  },
  {
    id: 42,
    name: "태안 안면도 튤립꽃축제",
    region: "충청/대전",
    address: "충청남도 태안군 안면읍 꽃지해안로 400",
    lat: 36.5029, lng: 126.3315,
    flowerIds: ["tulip"],
    peakMonth: 4, peakStartDate: "4.15", peakEndDate: "5.7",
    status: "없음",
    tags: ["튤립", "꽃지해수욕장", "세계축제", "태안"],
    description: "세계 5대 튤립 축제로 선정된 안면도 코리아플라워파크. 200여 종 백만 송이 튤립의 대장관.",
    parking: "꽃지해수욕장 및 코리아플라워파크 대형 주차장",
    tip: "꽃지해수욕장 할미·할아비 바위 낙조와 함께 관람을 추천합니다.",
    imageKeyword: "Taean World Tulip Flower Festival Anmyeondo"
  },
  {
    id: 43,
    name: "제천 청풍호 벚꽃길",
    region: "충청/대전",
    address: "충청북도 제천시 청풍면 청풍호로",
    lat: 37.0051, lng: 128.1755,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.8", peakEndDate: "4.18",
    status: "없음",
    tags: ["벚꽃", "청풍호", "케이블카", "제천"],
    description: "내륙의 바다 청풍호를 감싸쥐는 13km 벚꽃길과 청풍호반 케이블카 위에서 내려다보는 핑크빛 풍경.",
    parking: "청풍호반 케이블카 주차장 및 청풍문화재단지 주차장",
    tip: "청풍호반 케이블카를 타고 비봉산 정상에 오르면 호수 전체 벚꽃이 시원하게 조망됩니다.",
    imageKeyword: "Cheongpungho lake cherry blossom Jecheon"
  },
  {
    id: 44,
    name: "공주 계룡산 동학사 벚꽃길",
    region: "충청/대전",
    address: "충청남도 공주시 반포면 동학사1로",
    lat: 36.3533, lng: 127.2341,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.6", peakEndDate: "4.16",
    status: "없음",
    tags: ["벚꽃", "동학사", "계룡산", "사찰"],
    description: "계룡산 국립공원 들머리 4km 진입로가 벚꽃 터널을 이루어 계곡 물소리와 함께 걷는 명소.",
    parking: "동학사 상가 공영주차장",
    tip: "동학사 진입로 산채비빔밥 맛집 거리에서 봄나물 식사를 즐겨보세요.",
    imageKeyword: "Donghaksa temple Gyeryongsan cherry blossom Gongju"
  },
  {
    id: 45,
    name: "전주 완산칠봉 꽃동산 (겹벚꽃·철쭉)",
    region: "전라/광주",
    address: "전북특별자치도 전주시 완산구 공원길 84",
    lat: 35.8091, lng: 127.1402,
    flowerIds: ["kyupbeotkkot", "cheonjuk"],
    peakMonth: 4, peakStartDate: "4.20", peakEndDate: "5.5",
    status: "없음",
    tags: ["겹벚꽃", "철쭉", "분홍팝콘", "전주"],
    description: "전국 최고의 겹벚꽃과 철쭉 융단 동산. 겹겹이 묵직한 분홍 팝콘 겹벚꽃이 장관을 이룹니다.",
    parking: "완산공원 입구 주차장 (전주한옥마을에서 택시 10분)",
    tip: "전주한옥마을 여행 코스와 묶어서 방문하기 최고의 봄 꽃동산입니다.",
    imageKeyword: "Wansan park double cherry blossom Wansanchilbong Jeonju"
  },
  {
    id: 46,
    name: "고창 학원농장 유채꽃밭",
    region: "전라/광주",
    address: "전북특별자치도 고창군 공음면 학원농장길 150",
    lat: 35.3789, lng: 126.5412,
    flowerIds: ["yuche"],
    peakMonth: 4, peakStartDate: "4.15", peakEndDate: "5.5",
    status: "없음",
    tags: ["유채꽃", "청보리밭", "드라마촬영지", "고창"],
    description: "드넓은 30만 평 구릉지대를 가득 메우는 샛노란 유채꽃과 초록빛 청보리의 이색 듀엣 경관.",
    parking: "학원농장 메인 주차장 (무료)",
    tip: "드라마 '도깨비' 촬영지 메밀밭 원두막 주변에서 인생샷을 찍으세요.",
    imageKeyword: "Gochang Hakwon farm canola yellow green barley field"
  },
  {
    id: 47,
    name: "곡성 섬진강 기차마을 장미공원",
    region: "전라/광주",
    address: "전라남도 곡성군 곡성읍 기차마을로 232",
    lat: 35.2818, lng: 127.3005,
    flowerIds: ["jangmi"],
    peakMonth: 5, peakStartDate: "5.18", peakEndDate: "6.5",
    status: "없음",
    tags: ["장미", "기차마을", "증기기관차", "곡성"],
    description: "1,004종의 세계 장미가 피어나는 국내 대표 장미정원. 증기기관차를 타며 장미향을 맡을 수 있습니다.",
    parking: "섬진강 기차마을 대형 주차장",
    tip: "곡성 세계장미축제 기간에는 증기기관차 예약 후 방문하세요.",
    imageKeyword: "Gokseong Seomjingang train village rose garden"
  },
  {
    id: 48,
    name: "순천만 국가정원 봄꽃축제",
    region: "전라/광주",
    address: "전라남도 순천시 국가정원1호길 47",
    lat: 34.9317, lng: 127.5085,
    flowerIds: ["tulip", "beotkkot", "bootkkot"],
    peakMonth: 4, peakStartDate: "4.1", peakEndDate: "5.15",
    status: "없음",
    tags: ["국가정원", "튤립", "세계정원", "순천"],
    description: "대한민국 1호 국가정원. 네덜란드 정원의 튤립과 프랑스 정원의 붓꽃 등 세계 꽃 정원 대탐험.",
    parking: "순천만 국가정원 동문/서문 주차장",
    tip: "스카이큐브를 타고 순천만습지까지 한꺼번에 둘러보는 1일 코스 추천.",
    imageKeyword: "Suncheon Bay National Garden tulip spring festival"
  },
  {
    id: 49,
    name: "함평 핫스팟 작약·나비동산",
    region: "전라/광주",
    address: "전라남도 함평군 함평읍 곤재로 27",
    lat: 35.0664, lng: 126.5204,
    flowerIds: ["jakak", "yuche"],
    peakMonth: 5, peakStartDate: "5.5", peakEndDate: "5.25",
    status: "없음",
    tags: ["작약", "유채꽃", "나비축제", "함평"],
    description: "함평 엑스포공원과 들판을 가득 채우는 부귀의 대명사 작약꽃 군락과 나비의 화려한 날갯짓.",
    parking: "함평 엑스포공원 주차장",
    tip: "함평 나비대축제 기간 방문 시 나비 날리기 체험을 경험해보세요.",
    imageKeyword: "Hampyeong peony butterfly festival Jeollanamdo"
  },
  {
    id: 50,
    name: "경주 보문호수 벚꽃길",
    region: "경상/부산",
    address: "경상북도 경주시 보문로 424",
    lat: 35.8458, lng: 129.2783,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.2", peakEndDate: "4.12",
    status: "없음",
    tags: ["벚꽃", "보문단지", "호수", "경주"],
    description: "보문호 둘레 8km를 따라 고풍스러운 기와건물과 벚꽃 잎이 반짝이는 경주 최고의 봄맞이 명소.",
    parking: "보문단지 육부촌 공영주차장",
    tip: "보문정 정자 주변 벚꽃 반영 사진이 인스타그램 대표 인생샷 스팟입니다.",
    imageKeyword: "Gyeongju Bomun lake cherry blossom Bomunjeong"
  },
  {
    id: 51,
    name: "경주 불국사 겹벚꽃동산",
    region: "경상/부산",
    address: "경상북도 경주시 진현동 15-1 불국사 입구",
    lat: 35.7901, lng: 129.3323,
    flowerIds: ["kyupbeotkkot"],
    peakMonth: 4, peakStartDate: "4.18", peakEndDate: "5.2",
    status: "없음",
    tags: ["겹벚꽃", "불국사", "분홍팝콘", "경주"],
    description: "불국사 정문 주차장 일대 나지막한 언덕 전체가 분홍빛 겹벚꽃으로 채워지는 동화 같은 피크닉 장소.",
    parking: "불국사 공영주차장 (유료)",
    tip: "돗자리를 챙겨가 겹벚꽃 나무 아래 누워 봄 하늘과 분홍 팝콘을 감상하세요.",
    imageKeyword: "Bulguksa double cherry blossom picnic Gyeongju"
  },
  {
    id: 52,
    name: "창녕 남지 낙동강 유채단지",
    region: "경상/부산",
    address: "경상남도 창녕군 남지읍 남지리 낙동강변",
    lat: 35.3852, lng: 128.4719,
    flowerIds: ["yuche", "tulip"],
    peakMonth: 4, peakStartDate: "4.10", peakEndDate: "4.25",
    status: "없음",
    tags: ["유채꽃", "단일최대", "낙동강", "창녕"],
    description: "단일 면적 전국 최대(110만 ㎡)의 낙동강변 황금빛 유채꽃 바다. 한반도 지형 유채밭이 유명합니다.",
    parking: "남지 체육공원 유채축제 주차장 (무료)",
    tip: "풍차 포토존과 튜율립 정원이 함께 조성되어 도보 산책에 최고입니다.",
    imageKeyword: "Changnyeong Namji Nakdong river canola field"
  },
  {
    id: 53,
    name: "울산 태화강 국가정원 봄꽃축제",
    region: "경상/부산",
    address: "울산광역시 중구 태화강국가정원길 154",
    lat: 35.5492, lng: 129.3001,
    flowerIds: ["yuche", "jakak", "bootkkot"],
    peakMonth: 5, peakStartDate: "5.10", peakEndDate: "5.25",
    status: "없음",
    tags: ["태화강", "십리대숲", "국가정원", "울산"],
    description: "태화강변을 따라 피어나는 봄꽃과 십리대숲의 울창한 대나무길이 시원한 청량감을 주는 국가정원.",
    parking: "태화강 국가정원 공영주차장",
    tip: "은하수길 야간 대나무숲 라이트업과 봄꽃 조형물을 야간에 감상하세요.",
    imageKeyword: "Taehwagang National Garden spring flower Ulsan"
  },
  {
    id: 54,
    name: "거제 공곶이 수선화·동백",
    region: "경상/부산",
    address: "경상남도 거제시 일운면 와현리 87",
    lat: 34.8219, lng: 128.7291,
    flowerIds: ["yuche", "sansuyu"],
    peakMonth: 3, peakStartDate: "3.15", peakEndDate: "4.10",
    status: "없음",
    tags: ["수선화", "바다풍경", "동백", "거제도"],
    description: "남해 푸른 바다를 향해 계단식으로 늘어선 노란 수선화와 동백 터널이 인상적인 거제 8경.",
    parking: "예구마을 주차장 (도보 탐방 20분 소요)",
    tip: "동백나무 터널 계단을 지나 펼쳐지는 바다 수선화밭 풍경이 예술입니다.",
    imageKeyword: "Gonggotji narcissus flower Geoje island sea"
  },
  {
    id: 55,
    name: "제주 전농로 왕벚꽃거리",
    region: "제주",
    address: "제주특별자치도 제주시 삼도이동 전농로",
    lat: 33.5015, lng: 126.5245,
    flowerIds: ["wangbeotkkot"],
    peakMonth: 3, peakStartDate: "3.23", peakEndDate: "4.2",
    status: "없음",
    tags: ["왕벚꽃", "제주도심", "왕벚꽃축제", "제주"],
    description: "제주도 자생 왕벚나무 축제장. 터질 듯 거대한 왕벚꽃 송이가 도로 양쪽을 분홍빛 터널로 덮습니다.",
    parking: "주변 골목 및 서사라 공영주차장",
    tip: "제주 공항에서 차량 10분 거리로 제주 도착 직후나 출국 전 들르기 좋습니다.",
    imageKeyword: "Jeju Jeonnongro king cherry blossom street"
  },
  {
    id: 56,
    name: "제주 마노르블랑 수국정원",
    region: "제주",
    address: "제주특별자치도 서귀포시 안덕면 덕수남로102번길 46",
    lat: 33.2514, lng: 126.3112,
    flowerIds: ["suguk"],
    peakMonth: 5, peakStartDate: "5.20", peakEndDate: "7.10",
    status: "없음",
    tags: ["수국", "산방산", "제주카페", "인스타핫플"],
    description: "산방산을 배경으로 알록달록 몽글몽글 산방산 뷰 수국 산책로가 수천 평 피어나는 제주의 여름/봄 명소.",
    parking: "마노르블랑 전용 주차장",
    tip: "수국벽 길목 마노르블랑 액자 포토존에서 산방산을 배경으로 사진을 촬영하세요.",
    imageKeyword: "Manor Blanc hydrangea garden Sanbangsan Jeju"
  },
  {
    id: 57,
    name: "하동 최참판댁 평사리 유채꽃밭",
    region: "경상/부산",
    address: "경상남도 하동군 악양면 평사리",
    lat: 35.1528, lng: 127.7011,
    flowerIds: ["yuche"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.25",
    status: "없음",
    tags: ["유채꽃", "토지", "섬진강", "하동"],
    description: "소설 '토지'의 무대 평사리 들판에 사뿐히 내린 노란 유채꽃과 부부송(소나무)의 서정적인 시골 풍경.",
    parking: "최참판댁 입구 주차장",
    tip: "하동 십리벚꽃길 구경 후 최참판댁 들판 유채꽃까지 둘러보는 코스를 강추합니다.",
    imageKeyword: "Pyeongsari canola field Hadong Seomjingang"
  },
  {
    id: 58,
    name: "원주 반곡역·치악산 진달래",
    region: "강원",
    address: "강원특별자치도 원주시 달마중길 30",
    lat: 37.3218, lng: 127.9782,
    flowerIds: ["jindalrae", "beotkkot"],
    peakMonth: 4, peakStartDate: "4.5", peakEndDate: "4.15",
    status: "없음",
    tags: ["진달래", "간이역", "치악산", "원주"],
    description: "등록문화재 간이역인 옛 반곡역 기차역과 분홍빛 진달래·벚꽃이 빚어내는 아날로그 감성 명소.",
    parking: "반곡역 주차장",
    tip: "치악산 둘레길 트레킹과 함께 아날로그 기차역 감성샷을 촬영하세요.",
    imageKeyword: "Bangok station azalea cherry blossom Wonju"
  },
  {
    id: 59,
    name: "부산 삼락생태공원 벚꽃길",
    region: "경상/부산",
    address: "부산광역시 사상구 삼락동 29-46",
    lat: 35.1685, lng: 128.9712,
    flowerIds: ["beotkkot", "yuche"],
    peakMonth: 3, peakStartDate: "3.28", peakEndDate: "4.7",
    status: "없음",
    tags: ["벚꽃", "낙동강", "삼락공원", "부산"],
    description: "낙동강변을 따라 궤적을 그리는 5km의 긴 벚꽃 터널과 삼락 유채꽃밭이 만나는 부산 최고의 대형 생태공원.",
    parking: "삼락생태공원 P1~P9 주차장 (무료)",
    tip: "낙동강 노을빛이 내릴 때 벚꽃 터널 사이로 산책하면 환상적입니다.",
    imageKeyword: "Samnak ecological park cherry blossom Busan"
  },
  {
    id: 60,
    name: "광주 운천저수지 벚꽃길",
    region: "전라/광주",
    address: "광주광역시 서구 쌍촌동 866",
    lat: 35.1512, lng: 126.8524,
    flowerIds: ["beotkkot"],
    peakMonth: 4, peakStartDate: "4.1", peakEndDate: "4.10",
    status: "없음",
    tags: ["벚꽃", "저수지", "광주", "도심"],
    description: "광주 도심 한가운데 저수지를 한 바퀴 둘러싼 벚꽃 수변 데크길과 야간 수중 분수 조명 명소.",
    parking: "운천저수지 주변 공영주차장 및 지하철 운천역 이용",
    tip: "지하철 1호선 운천역 도보 3분 거리로 접근성이 매우 뛰어납니다.",
    imageKeyword: "Uncheon reservoir cherry blossom Gwangju"
  }
];

// 지역별 명소 필터
export function getSpotsByRegion(region: Region): Spot[] {
  return SPOTS.filter(s => s.region === region);
}

// 꽃 종류별 명소 필터
export function getSpotsByFlower(flowerId: string): Spot[] {
  return SPOTS.filter(s => s.flowerIds.includes(flowerId));
}

// 월별 명소 필터
export function getSpotsByMonth(month: number): Spot[] {
  return SPOTS.filter(s => s.peakMonth === month);
}

export const REGIONS: Region[] = ["서울/경기", "강원", "충청/대전", "전라/광주", "경상/부산", "제주"];
